apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cvg3d5e53-java-springboot
  janus-idp.io/tekton: cvg3d5e53-java-springboot
  backstage.io/kubernetes-id: cvg3d5e53-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cvg3d5e53-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
